### ISSUE TITLE
Database report

### ISSUE THREAD

**Issue by shadowcomer** [shadowcomer/CatLing#11]
Elaborate a report with all the information required in related issues to the milestone.
The report must include a critical analysis of the database within the AI context, comparing the use expectations against reality's possibilities based on the results of testing.
The report must conclude with the best possible, and recommended, course of action.

**Comment by Cazaril** [comment]
Need pair review of the document proposed. It may need some more work or maybe something is missing, but all the basics are there.
Please, check it and commment.
