### ISSUE TITLE
Non-meaningful names in Log

### ISSUE THREAD

**Issue by shadowcomer** [shadowcomer/CatLing#14]
Please, use meaningful names when you're working. Everything that's done has to be reviewed before adding it in, and It's a pain to understand when everything is obfuscated.

**Comment by shadowcomer** [comment]
Also: remember to pull some changes I made first, and you're working on the old version of the project so you should first make sure everything gets correctly updated.

**Comment by shadowcomer** [comment]
I wanted to add: code in english and comment in english (this is open source, after all)

**Comment by shadowcomer** [comment]
Any updates about this issue?

**Comment by shadowcomer** [comment]
Jpg3D, anything to report back? This should be solved soon to be able to move on with stuff.

**Comment by Jpg3D** [comment]
Names checked.
